spring:
  application:
    name: springboot-backend-app
  data:
    redis:
      host: 192.168.0.2
      port: 6380
      password: 123456
      database: 0
  datasource:
    url: jdbc:postgresql://192.168.0.2:5469/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: springboot_backend
jwt:
  secret: SpringBootBackend
  expire: 86400000
rsa:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsoL3pUEX5ZiXrYkjHFeGfeHJGx2z1TEpYcE2n/SKe2S6i/GYhnkZSd7LDrvnBpYt8qyMSwSh5iTNTKubq3d80iF01KrPD7r/6Dx6hKXhZ0dy3CFwRFr5cywO2ZfEXFnnYLO0maNtsb0ZdexPRIyl4TrCjv00c+3n7nWfVW1DDOMF77pIPMhp0kcM1SXee7U6oKn+XZTayUiivjtNS/QRjTt7JBtT6gmGQYvowZ0fUeN/QDWyzCgoMY40BJIIHJ8utHis65u9Y0uoSyaNW4pZzIEtb6N7ascDFPGgmSpst27ysRl9UbbZIOYcyUhvUmUF3D/ZXeT4wq4+epWZsIrU9QIDAQAB
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCygvelQRflmJetiSMcV4Z94ckbHbPVMSlhwTaf9Ip7ZLqL8ZiGeRlJ3ssOu+cGli3yrIxLBKHmJM1Mq5urd3zSIXTUqs8Puv/oPHqEpeFnR3LcIXBEWvlzLA7Zl8RcWedgs7SZo22xvRl17E9EjKXhOsKO/TRz7efudZ9VbUMM4wXvukg8yGnSRwzVJd57tTqgqf5dlNrJSKK+O01L9BGNO3skG1PqCYZBi+jBnR9R439ANbLMKCgxjjQEkggcny60eKzrm71jS6hLJo1bilnMgS1vo3tqxwMU8aCZKmy3bvKxGX1Rttkg5hzJSG9SZQXcP9ld5PjCrj56lZmwitT1AgMBAAECggEABQXwGmDaCiEV8jv/1m4qFS8TfdADUvZMBU8EDqfkIQkabLyy1OSMecqAqUdP/sdJaguWnmJ2Jyfq9QOGi7fUNdow05kuNBxIKOH8H/EbsNB5uB24GdxQ1P+s4qJFfsRy4S2Stpi631EEaeU+l8hjaefsOKIsZdoQeDfWxiHJzLonU0y8TRas17RMwK3sm21fsKqbW4LsRUgnOz9UDjtdnhKYAU7A4CYF/zhvNrShBcfSkzzYveMyJzhi4/cTCXuctJzMqQUZA1i3iPndlqoGD9Nqnty1gCCn6Pa0lbpOJmxYW0wix4bsMp9yNNf1LMFyhrDsJJMtFkz9YB+BTZ3bswKBgQDdVvVQmAMa5OTtf+WxyT8VAV6jC14yrjH7hW6iFIogE0rj5PzWq1P8bP5Vfj6QrJUt1M8vqo5/UKQ3DPACZm6qdvDd+bHzQ7dPSyzZloS8+ryREQsoXh+b+AIkwSBUo/8p4/HnDu8Bfzt2U4zfjH6UwCe38/5MhYQqpVa7LODJdwKBgQDOdx8FmI7m5r8imRtw7DYux000TCLWEmB0i27bQvg6P2ZF3iSv+QOr8ffq4gjsGsn6GInAUQ+UC266K8860vMz/yHJdrOH8F+LaN1f8ZbmBP6BK02RYJ2uMYKxBQ3h1iZnhI4LsyW4XlIh5Ya3Zgfbfjii89z00d87K/PrMvdv8wKBgBgUj9fW0e+pG2bjVUAEXwKQBZXDdNoarYFpwOGNToGy16D3lrJcLWT3DqyKcZAX1psH3gqXia08PsFmfO4l6sBM9GOR+NQ4d8b+rMB3abWNqdo2enpH0zSKxODuye+rb+VE0VqL+2C0UOnMqTTg+hyA01FmEDKPDBP/rPHsLgB9AoGBAKzl8KKdCT6wCWwNz38XMKCn4i1jfODMbt3qTiFrybftk9X6m7qJy9tYPIcEVvhxzqaTmfflaihOEqHxQg8+zM/EXiT6NIoob7qtTIWmKPnjQMYm30RZJnLTn2BinSd8UJjr1pBRq8rjoeAk+FXpKbdT0lYT5ftXLZu9yPwzqCalAoGAZdL20aPCH03hC2tlIaBaEeRnhgXvL5yQ2tVamsZjFWOblo8RWiSCo5euXiyYPvpxa+G/xCu7H9W8aPtwsEOnjA8Dz8VUgKcKPCi0JElnTgRcWtk+JD+ccnXnjgFsjQk86025rRdKUV3/LvL14ztCVIBsThj6OlgfyL1Wc6Q7UJE=
interceptor:
  include-paths:
    - /api/**
  exclude-paths:
    - /api/auth/login
    - /api/auth/public-key