version: '3.8'

services:
  my-springboot-app:
    image: openjdk:25-ea-25-jdk-slim
    container_name: java-app
    restart: unless-stopped
    ports:
      - "9080:8080"
    volumes:
      # 挂载应用 JAR 和配置文件目录
      - ./:/app
    working_dir: /app
    command: >
      java
      -jar /app/app.jar
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
